/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatec.aula;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author gabri
 */
public class DespesasJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DespesasJFrame
     */
    public DespesasJFrame() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        descricaoLabel = new javax.swing.JLabel();
        descricaoTextField = new javax.swing.JTextField();
        valorLabel = new javax.swing.JLabel();
        valorTextField = new javax.swing.JTextField();
        categoriaLabel = new javax.swing.JLabel();
        categoriaComboBox = new javax.swing.JComboBox<>();
        tipoLabel = new javax.swing.JLabel();
        receitaRadioButton = new javax.swing.JRadioButton();
        despesaRadioButton = new javax.swing.JRadioButton();
        dataLabel = new javax.swing.JLabel();
        dataDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        despesasTable = new javax.swing.JTable();
        labelPanel = new javax.swing.JPanel();
        calcdespesasPanel = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        tiporeceitaPanel = new javax.swing.JPanel();
        categoriaPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        despesaLabel = new javax.swing.JLabel();
        despesatotalLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        saldoLabel = new javax.swing.JLabel();
        saldototalLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        receitaLabel2 = new javax.swing.JLabel();
        receitatotalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ExercícioDespesas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(241, 242, 246));

        descricaoLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        descricaoLabel.setText("Descrição");

        descricaoTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        descricaoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descricaoTextFieldKeyPressed(evt);
            }
        });

        valorLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        valorLabel.setText("Valor");

        valorTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        categoriaLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        categoriaLabel.setText("Categoria");

        categoriaComboBox.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        categoriaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compras", "Moradia", "Saúde", "Transporte", "Estudo", "Lazer", "Alimentação", "Outros", "Receita" }));

        tipoLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tipoLabel.setText("Tipo");

        buttonGroup1.add(receitaRadioButton);
        receitaRadioButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        receitaRadioButton.setSelected(true);
        receitaRadioButton.setText("Receita/Crédito");

        buttonGroup1.add(despesaRadioButton);
        despesaRadioButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        despesaRadioButton.setText("Despesa/Débito");

        dataLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dataLabel.setText("Data");

        dataDateChooser.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        despesasTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        despesasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Valor", "Data", "Tipo", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        despesasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                despesasTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(despesasTable);

        labelPanel.setBackground(new java.awt.Color(52, 152, 219));

        calcdespesasPanel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        calcdespesasPanel.setForeground(new java.awt.Color(255, 255, 255));
        calcdespesasPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calcdespesasPanel.setText("Cálculo de despesas");

        javax.swing.GroupLayout labelPanelLayout = new javax.swing.GroupLayout(labelPanel);
        labelPanel.setLayout(labelPanelLayout);
        labelPanelLayout.setHorizontalGroup(
            labelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calcdespesasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        labelPanelLayout.setVerticalGroup(
            labelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(calcdespesasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        addButton.setBackground(new java.awt.Color(76, 209, 55));
        addButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/add-24 (1).png"))); // NOI18N
        addButton.setText("Adicionar");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        excluirButton.setBackground(new java.awt.Color(232, 65, 24));
        excluirButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        excluirButton.setForeground(new java.awt.Color(255, 255, 255));
        excluirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/delete-24 (1).png"))); // NOI18N
        excluirButton.setText("Excluir");
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(25, 42, 86));
        saveButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/save-24.png"))); // NOI18N
        saveButton.setText("Salvar");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        loadButton.setBackground(new java.awt.Color(87, 96, 111));
        loadButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loadButton.setForeground(new java.awt.Color(255, 255, 255));
        loadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/data-transfer-download-32.png"))); // NOI18N
        loadButton.setText("Carregar");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        refreshButton.setBackground(new java.awt.Color(53, 59, 72));
        refreshButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/icons/sinchronize-24 (1).png"))); // NOI18N
        refreshButton.setText("Atualizar");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        tiporeceitaPanel.setPreferredSize(new java.awt.Dimension(600, 303));

        javax.swing.GroupLayout tiporeceitaPanelLayout = new javax.swing.GroupLayout(tiporeceitaPanel);
        tiporeceitaPanel.setLayout(tiporeceitaPanelLayout);
        tiporeceitaPanelLayout.setHorizontalGroup(
            tiporeceitaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );
        tiporeceitaPanelLayout.setVerticalGroup(
            tiporeceitaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        categoriaPanel.setPreferredSize(new java.awt.Dimension(600, 322));

        javax.swing.GroupLayout categoriaPanelLayout = new javax.swing.GroupLayout(categoriaPanel);
        categoriaPanel.setLayout(categoriaPanelLayout);
        categoriaPanelLayout.setHorizontalGroup(
            categoriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        categoriaPanelLayout.setVerticalGroup(
            categoriaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(231, 76, 60));

        despesaLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        despesaLabel.setForeground(new java.awt.Color(255, 255, 255));
        despesaLabel.setText("Despesa Total");

        despesatotalLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        despesatotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        despesatotalLabel.setText("R$ 0.00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(despesaLabel)
                    .addComponent(despesatotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(despesaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(despesatotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(52, 152, 219));

        saldoLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        saldoLabel.setForeground(new java.awt.Color(255, 255, 255));
        saldoLabel.setText("Saldo total");

        saldototalLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        saldototalLabel.setForeground(new java.awt.Color(255, 255, 255));
        saldototalLabel.setText("R$ 0.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saldoLabel)
                    .addComponent(saldototalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(saldoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saldototalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(76, 209, 55));

        receitaLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        receitaLabel2.setForeground(new java.awt.Color(255, 255, 255));
        receitaLabel2.setText("Receita Total");

        receitatotalLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        receitatotalLabel.setForeground(new java.awt.Color(255, 255, 255));
        receitatotalLabel.setText("R$ 0.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receitaLabel2)
                    .addComponent(receitatotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(receitaLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(receitatotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(descricaoLabel)
                                    .addComponent(categoriaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valorTextField)
                                    .addComponent(categoriaComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(valorLabel)
                                    .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(89, 89, 89)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(receitaRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(despesaRadioButton)
                                    .addComponent(dataDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataLabel)
                                    .addComponent(loadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tipoLabel)))
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(descricaoTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(excluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(tiporeceitaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(categoriaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(labelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(labelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(descricaoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descricaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataLabel)
                            .addComponent(valorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dataDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(categoriaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoriaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(tipoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(receitaRadioButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(despesaRadioButton)
                        .addGap(10, 10, 10)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tiporeceitaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(categoriaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private DefaultTableModel modelo = new DefaultTableModel();

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:

        try {

            String valor = valorTextField.getText();

            double valorfinal = Double.parseDouble(valor.replace(",", ".").trim());

            if (receitaRadioButton.isSelected()) {

                receitatotal += valorfinal;

            } else {
                despesatotal += valorfinal;
            }

            receitatotalLabel.setText(String.valueOf(String.format("R$ %.2f", receitatotal)));
            despesatotalLabel.setText(String.valueOf(String.format("R$ %.2f", despesatotal)));
            saldototalLabel.setText(String.valueOf(String.format("R$ %.2f", receitatotal - despesatotal)));

            String tipo = null;

            String desc = descricaoTextField.getText();

            DateFormat df = new SimpleDateFormat("dd/MM/YYYY");
            String data = df.format(dataDateChooser.getDate());

            if (receitaRadioButton.isSelected()) {
                tipo = "Receita";

            } else {
                tipo = "Despesa";
            }

            String categoria = String.valueOf(categoriaComboBox.getSelectedItem());

            modelo = (DefaultTableModel) despesasTable.getModel();
            Object[] linha = {desc, valorfinal, data, tipo, categoria};
            modelo.addRow(linha);

            despesasTable.setModel(modelo);

            barchart();
            piechart();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Favor adicione valores",
                    "Valores",
                    JOptionPane.WARNING_MESSAGE);
        }

        novodado();

    }//GEN-LAST:event_addButtonActionPerformed

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed
        // TODO add your handling code here:

        int linhaSelecionada = despesasTable.getSelectedRow();
        if (linhaSelecionada < 0) {
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) despesasTable.getModel();

        String tipo = String.valueOf(modelo.getValueAt(linhaSelecionada, 3));
        String valor = String.valueOf(modelo.getValueAt(linhaSelecionada, 1));

        valor = valor.replace(',', '.').trim();
        Double valorfinal = Double.parseDouble(valor);

        if ("Receita".equals(tipo)) {
            receitatotal -= valorfinal;
        } else {
            despesatotal -= valorfinal;
        }

        receitatotalLabel.setText(String.valueOf(String.format("R$ %.2f", receitatotal)));
        despesatotalLabel.setText(String.valueOf(String.format("R$ %.2f", despesatotal)));
        saldototalLabel.setText(String.valueOf(String.format("R$ %.2f", receitatotal - despesatotal)));

        modelo.removeRow(linhaSelecionada);
        novodado();

    }//GEN-LAST:event_excluirButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        descricaoTextField.requestFocus();

    }//GEN-LAST:event_formWindowOpened

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:

        String caminho = "src\\br\\edu\\fatec\\aula\\cadastro.txt";

        File file = new File(caminho);

        try {
            try (FileWriter fw = new FileWriter(file); BufferedWriter bw = new BufferedWriter(fw)) {

                for (int i = 0; i < despesasTable.getRowCount(); i++) {
                    for (int j = 0; j < despesasTable.getColumnCount(); j++) {
                        bw.write(despesasTable.getValueAt(i, j).toString() + "|");
                    }
                    bw.newLine();
                }
            }

            JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!", "Sucesso", JOptionPane.OK_OPTION);

        } catch (IOException ex) {
            Logger.getLogger(DespesasJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:

        String caminho = "src\\br\\edu\\fatec\\aula\\cadastro.txt";

        File file = new File(caminho);

        FileReader fr;
        try {
            fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);

            DefaultTableModel model = (DefaultTableModel) despesasTable.getModel();
            Object[] linha = br.lines().toArray();

            for (Object linha2 : linha) {
                String[] row = linha2.toString().split("[|]");
                model.addRow(row);
                String type = row[3];
                Double value = Double.parseDouble(row[1]);

                if ("Receita".equals(type)) {
                    receitatotal += value;
                } else {
                    despesatotal += value;
                }
            }

            receitatotalLabel.setText(String.valueOf(String.format("R$ %.2f", receitatotal)));
            despesatotalLabel.setText(String.valueOf(String.format("R$ %.2f", despesatotal)));
            saldototalLabel.setText(String.valueOf(String.format("R$ %.2f", receitatotal - despesatotal)));

            despesasTable.setModel(model);

            barchart();
            piechart();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "batata", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_loadButtonActionPerformed

    private void despesasTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_despesasTableMouseClicked
        // TODO add your handling code here:

        int linhaSelecionada = despesasTable.getSelectedRow();
        modelo = (DefaultTableModel) despesasTable.getModel();

        String desc = String.valueOf(modelo.getValueAt(linhaSelecionada, 0));
        String valor = String.valueOf(modelo.getValueAt(linhaSelecionada, 1));
        String data = String.valueOf(modelo.getValueAt(linhaSelecionada, 2));
        String tipo = String.valueOf(modelo.getValueAt(linhaSelecionada, 3));
        String categoria = String.valueOf(modelo.getValueAt(linhaSelecionada, 4));

        descricaoTextField.setText(desc);
        valorTextField.setText(valor);
        try {
            Date date1 = new SimpleDateFormat("dd/MM/yyyy").parse(data);
            dataDateChooser.setDate(date1);
        } catch (ParseException ex) {
            Logger.getLogger(DespesasJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if ("Receita".equals(tipo)) {
            receitaRadioButton.setSelected(true);
        } else {
            despesaRadioButton.setSelected(true);
        }

        categoriaComboBox.setSelectedItem(categoria);

    }//GEN-LAST:event_despesasTableMouseClicked

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:

        int linhaSelecionada = despesasTable.getSelectedRow();
        modelo = (DefaultTableModel) despesasTable.getModel();

        if (linhaSelecionada >= 0) {

            modelo.setValueAt(descricaoTextField.getText(), linhaSelecionada, 0);
            modelo.setValueAt(valorTextField.getText(), linhaSelecionada, 1);
            modelo.setValueAt(dataDateChooser.getDate(), linhaSelecionada, 2);

            if (receitaRadioButton.isSelected()) {
                modelo.setValueAt("Receita", linhaSelecionada, 3);
            } else {
                modelo.setValueAt("Despesa", linhaSelecionada, 3);
            }

            modelo.setValueAt(categoriaComboBox.getSelectedItem(), linhaSelecionada, 4);

            piechart();
            barchart();

        } else {
            JOptionPane.showMessageDialog(null, "Error", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void descricaoTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descricaoTextFieldKeyPressed
        // TODO add your handling code here:

        int key = evt.getKeyCode();

        if (key == KeyEvent.VK_ENTER) {
            addButton.doClick();
        }
    }//GEN-LAST:event_descricaoTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DespesasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DespesasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DespesasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DespesasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DespesasJFrame().setVisible(true);
            }
        });
    }

    Double receitatotal = 0.0;
    Double despesatotal = 0.0;
    Double saldototal = 0.0;

    void novodado() {
        descricaoTextField.setText("");
        valorTextField.setText("");
        dataDateChooser.setDate(null);
        categoriaComboBox.setSelectedIndex(0);
    }

    
    @SuppressWarnings("empty-statement")
    public void saveTable() throws Exception {
        try (BufferedWriter bfw = new BufferedWriter(new FileWriter("Data.txt"))) {
            for (int i = 1; i < despesasTable.getRowCount(); i++) {
                bfw.newLine();
                for (int j = 1; j < despesasTable.getColumnCount(); j++) {
                    bfw.write((String) (despesasTable.getValueAt(i, j)));
                    bfw.write("\t");;
                }
            }
        }
    }

    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("bank.png")));
    }

    private void barchart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        Double rectable = 0.0;
        Double desptable = 0.0;

        for (int i = 0; i < modelo.getRowCount(); i++) {
            String valortable = String.valueOf(modelo.getValueAt(i, 1));
            String tipotable = String.valueOf(modelo.getValueAt(i, 3));

            if ("Receita".equals(tipotable)) {
                rectable += Double.parseDouble(valortable);
            } else {
                desptable += Double.parseDouble(valortable);
            }

        }

        dataset.addValue(rectable, "Receita", "");
        dataset.addValue(desptable, "Despesa", "");

        JFreeChart xy = ChartFactory.createBarChart("TIPO", "2018", "VALORES", dataset, PlotOrientation.VERTICAL,
                true,
                true,
                false);

        ChartPanel panel = new ChartPanel(xy);
        int width = tiporeceitaPanel.getWidth();
        int height = tiporeceitaPanel.getHeight();

        panel.setPreferredSize(new Dimension(width, height));

        tiporeceitaPanel.setLayout(new BorderLayout());
        tiporeceitaPanel.add(panel, BorderLayout.CENTER);
        tiporeceitaPanel.validate();
    }

    private void piechart() {
        DefaultPieDataset piedataset = new DefaultPieDataset();

        Double[] category = new Double[9];

        for (int i = 0; i < 9; i++) {

            category[i] = 0.0;
        }

        for (int i = 0; i < despesasTable.getRowCount(); i++) {
            String categoriatable = String.valueOf(modelo.getValueAt(i, 4));
            String value = String.valueOf(modelo.getValueAt(i, 1));
            Double num = Double.parseDouble(value);
            switch (categoriatable) {
                case "Compras":
                    category[0] += num;
                    break;
                case "Moradia":
                    category[1] += num;
                    break;
                case "Saúde":
                    category[2] += num;
                    break;
                case "Transporte":
                    category[3] += num;
                    break;
                case "Estudo":
                    category[4] += num;
                    break;
                case "Lazer":
                    category[5] += num;
                    break;
                case "Alimentação":
                    category[6] += num;
                    break;
                case "Outros":
                    category[7] += num;
                    break;
                case "Receita":
                    category[8] += num;
                    break;
                default:
                    break;
            }

        }

        if (category[0] > 0.0) {

            piedataset.setValue("Compras", category[0]);
        }

        if (category[1] > 0.0) {
            piedataset.setValue("Moradia", category[1]);
        }

        if (category[2] > 0.0) {
            piedataset.setValue("Saúde", category[2]);
        }
        if (category[3] > 0.0) {
            piedataset.setValue("Transporte", category[3]);
        }
        if (category[4] > 0.0) {
            piedataset.setValue("Estudo", category[4]);
        }
        if (category[5] > 0.0) {
            piedataset.setValue("Lazer", category[5]);
        }
        if (category[6] > 0.0) {
            piedataset.setValue("Alimentação", category[6]);
        }
        if (category[7] > 0.0) {
            piedataset.setValue("Outros", category[7]);
        }
        if (category[8] > 0.0) {
            piedataset.setValue("Receita", category[8]);
        }

        JFreeChart pie = ChartFactory.createPieChart("Categoria",
                piedataset,
                true,
                true,
                false);

        // PARTE PADRÃO DE TODOS OS GRÁFICOS 
        ChartPanel panel2 = new ChartPanel(pie);
        int width2 = categoriaPanel.getWidth();
        int height2 = categoriaPanel.getHeight();

        panel2.setPreferredSize(new Dimension(width2, height2));

        categoriaPanel.setLayout(new BorderLayout());
        categoriaPanel.add(panel2, BorderLayout.CENTER);
        categoriaPanel.validate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel calcdespesasPanel;
    private javax.swing.JComboBox<String> categoriaComboBox;
    private javax.swing.JLabel categoriaLabel;
    private javax.swing.JPanel categoriaPanel;
    private com.toedter.calendar.JDateChooser dataDateChooser;
    private javax.swing.JLabel dataLabel;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JTextField descricaoTextField;
    private javax.swing.JLabel despesaLabel;
    private javax.swing.JRadioButton despesaRadioButton;
    private javax.swing.JTable despesasTable;
    private javax.swing.JLabel despesatotalLabel;
    private javax.swing.JButton excluirButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel labelPanel;
    private javax.swing.JButton loadButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel receitaLabel2;
    private javax.swing.JRadioButton receitaRadioButton;
    private javax.swing.JLabel receitatotalLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel saldoLabel;
    private javax.swing.JLabel saldototalLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel tipoLabel;
    private javax.swing.JPanel tiporeceitaPanel;
    private javax.swing.JLabel valorLabel;
    private javax.swing.JTextField valorTextField;
    // End of variables declaration//GEN-END:variables

}
